version: "3.8"
services:

  goservices-category:
    build: "."
    container_name: goservices-category
    image: naufalhakm/library-api-category:v2
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: library
    ports:
      - "8084:8084"  # REST API
    restart: always

networks:
  default:
    external:
      name: nginx-proxy